language: cpp
compiler:
- gcc

before_install:
  # g++4.8.1


  - sudo apt-get update -qq

before_install:

  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu/ trusty main restricted" -y
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - sudo apt-get install libboost-thread-dev libboost-system-dev libboost-test-dev
  - sudo dpkg -S /usr/include/boost/version.hpp
  - sudo apt-get install cmake

# test test test
script: 
  - mkdir build && cd build && cmake ..
  - make -j4 && ./tests/boosttest-tests-samogwas_test_suite 

notifications:
  email:
    recipients: license.to.kill.dr.no@gmail.com 
    on_success: change
    on_failure: always


