language: cpp
compiler:
- gcc


before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu/ trusty main restricted" -y
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi
  - if [ "$CXX" = "g++" ]; then export CC="gcc-4.8" CXX="g++-4.8"; fi

  - sudo apt-get install -yqq git cmake autoconf libtool python-dev



install:
  # Install boost
  - wget --no-verbose --output-document=boost-trunk.tar.bz2 http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.bz2/download
  - export BOOST_ROOT="$TRAVIS_BUILD_DIR/../boost-trunk"
  - export CMAKE_MODULE_PATH="$BOOST_ROOT"
  - mkdir -p $BOOST_ROOT
  - tar jxf boost-trunk.tar.bz2 --strip-components=1 -C $BOOST_ROOT
  - (cd $BOOST_ROOT; ./bootstrap.sh --with-libraries=filesystem,system,regex,program_options,test,log,thread)
  - (cd $BOOST_ROOT; ./b2 --prefix=$BOOST_ROOT --j7 cxxflags="-std=c++11" threading=multi link=static  -d0 install)

# test test test
script: 
  - $CXX --version
  - mkdir -p build && cd build && cmake .. -DBOOST_ROOT=$BOOST_ROOT -DCMAKE_INSTALL_PREFIX:PATH=~
  - make -j7 
  - ./tests/boosttest-tests-samogwas_test_suite 

notifications:
  email: 
    recipients: 
      - license.to.kill.dr.no@gmail.com
      - jules.teulade@gmail.com
    on_success: change
    on_failure: always


