ProBT: plDataDescriptor Class Reference
plDataDescriptor Class Reference abstract
This abstract template class defines a sequential data container.
Public Member Functions
plDataDescriptor ()
Constructor.
bool is_ok () const
Returns true if the initialization (construction) is OK.
virtual ~plDataDescriptor ()
Destructor.
virtual unsigned int get_num_fields () const =0
Returns the number of fields (columns).
virtual void rewind ()=0
Rewinds the container to go back to its begining.
virtual bool get_data_record (const plValues *&data_values, const std::vector< bool > *&data_definition)=0
Get the next data record (row) and advances by one record in the data.
bool get_data_record_value (plValues &data_values, std::vector< bool > &data_definition)
Get the next data record (row) and advances by one record in the data.
template<typename T >
bool get_data_row (std::vector< T > &data_row, std::vector< bool > &data_row_def)
Get the next data record (row) as an STL vector and advances by one record in the data.
bool get_next_defined_values (plValues &data_values)
Get the defined values from the next data record (row) and advances by one record in the data.
template<typename T >
void get_data_matrix (std::vector< std::vector< T > > &data_matrix, unsigned int n=std::numeric_limits< unsigned int >::max())
Fills the data matrix corresponding to the data container.
template<typename T >
void get_data_matrix (std::vector< std::vector< T > > &data_matrix, std::vector< std::vector< bool > > &def_matrix, unsigned int n=std::numeric_limits< unsigned int >::max())
Fills the data matrix (and the corresponding definition matrix) corresponding to the data container.
virtual void get_data_range (std::vector< plFloat > &min_vals, std::vector< plFloat > &max_vals)
Returns the range of the data.
virtual unsigned int get_simple_stats (std::vector< plFloat > &min_vals, std::vector< plFloat > &max_vals, std::vector< plFloat > &mean_vals, std::vector< plFloat > &stdev_vals, std::vector< unsigned int > &n, unsigned int &ncomplete_rows)
Computes some simple stats on the data.
template<typename T >
void get_column_values (unsigned int n, std::vector< T > &column_vals)
Get a column vector.
template<typename T >
void get_column_values (unsigned int n, std::vector< T > &column_vals, std::vector< bool > &column_defs)
Get a column vector and the corresponding definition values.
template<typename T >
void get_variable_values (const plSymbol &variable, std::vector< T > &column_vals)
Get a column vector.
template<typename T >
void get_variable_values (const plSymbol &variable, std::vector< T > &column_vals, std::vector< bool > &column_defs)
Get a column vector and the corresponding definition values.
virtual bool validate (std::vector< unsigned int > &erroneous_lines)
Validate the data set by checking that the provided values are compatible with the types of the given variable conjunction associaded to the data descriptor.
virtual unsigned int get_n_records ()
Get the number of records (rows) in the data set.
virtual plVariablesConjunction observed_variables ()=0
Get the variables associated to the descriptor.
virtual std::ostream & print_head (unsigned int n=20, std::ostream &sout=std::cout, char sep= '\t')
Prints the header and the 'n' first rows in the output stream 'sout'.
virtual void print_head (const std::string &file, unsigned int n=20, char sep= '\t')
Prints the header and the 'n' first rows in the file 'file'.
virtual std::ostream & print_simple_stats (std::ostream &sout=std::cout, char sep= '\t')
Prints some simple statistic of the data.
virtual void print_simple_stats (const std::string &file, char sep= '\t')
Prints some simple statistic of the data.
std::vector< std::vector
< plFloat > > use_for_discretization (const std::vector< plVariableDiscretizer * > &discretizers, const std::vector< size_t > &variable_columns)
Return the discretization intervals for the variables corresponding to columns variable_columns according to this data set.
std::vector< plFloat > use_for_discretization (plVariableDiscretizer *discretizer, size_t variable_column)
Return the discretization intervals for the variable corresponding to column variable_column according to this data set.
Public Member Functions inherited from plObject
plObject ()
Constructor.
virtual ~plObject ()
Destroys the object.
std::string to_string (std::ostringstream *s=0) const
Returns the object as a string.
Protected Member Functions
virtual void Output (std::ostream &os) const
Writes the object at the out stream.
Detailed Description
This abstract template class defines a sequential data container.
This data descriptor is intended to be used with learning functions such as plLearnObject::learn(), plLearner::learn_model_parameters(), and plEMLearner::run().
Constructor & Destructor Documentation
virtual plDataDescriptor::~plDataDescriptor () inline virtual
Destructor.
Member Function Documentation
template<typename T > void plDataDescriptor::get_column_values (unsigned int n, std::vector< T > & column_vals) inline
Get a column vector.
Parameters
[in] n column number.
[out] column_vals the returned column vector.
template<typename T > void plDataDescriptor::get_column_values (unsigned int n, std::vector< T > & column_vals, std::vector< bool > & column_defs) inline
Get a column vector and the corresponding definition values.
Parameters
[in] n column number.
[out] column_vals the returned column vector.
[out] column_defs the corresponding definition values.
template<typename T > void plDataDescriptor::get_data_matrix (std::vector< std::vector< T > > & data_matrix, unsigned int n = std::numeric_limits<unsigned int>::max()) inline
Fills the data matrix corresponding to the data container.
Parameters
[out] data_matrix the returned data matrix.
[in] n the number of rows (data records) to be copied
References plValues::size().
template<typename T > void plDataDescriptor::get_data_matrix (std::vector< std::vector< T > > & data_matrix, std::vector< std::vector< bool > > & def_matrix, unsigned int n = std::numeric_limits<unsigned int>::max()) inline
Fills the data matrix (and the corresponding definition matrix) corresponding to the data container.
Parameters
[out] data_matrix the returned data matrix.
[out] def_matrix the corresponding definition matrix.
[in] n the number of rows (data records) to be copied
References plValues::size().
virtual void plDataDescriptor::get_data_range (std::vector< plFloat > & min_vals, std::vector< plFloat > & max_vals) virtual
Returns the range of the data.
Parameters
[out] min_vals the minimal value found in the data container for each data field (column).
[out] max_vals the maximal value found in the data container for each data field (column).
virtual bool plDataDescriptor::get_data_record (const plValues *& data_values, const std::vector< bool > *& data_definition) pure virtual
Get the next data record (row) and advances by one record in the data.
Parameters
[out] data_values an array of values for all variables described in the record.
[out] data_definition a vector stating, for each value in data_values, whether it's defined or not.
Returns
false iif the end of the container is reached.
The returned pointers are managed internally: you should not attempt to delete them, or use them after another call to get_data_record(). Also, you should not use them when get_data_record() returns false.
Implemented in plCSVFileDataDescriptor, plCSVDataDescriptor, plMysqlDataDescriptor, plODBCDataDescriptor, and plMatrixDataDescriptor< T >.
bool plDataDescriptor::get_data_record_value (plValues & data_values, std::vector< bool > & data_definition)
Get the next data record (row) and advances by one record in the data.
This function make a copy into the two output parameters and is then less efficient than those returning pointers. It's intended to be used with the Python, .net, and Java bindings.
Parameters
[out] data_values an array of values for all variables described in the record.
[out] data_definition a vector stating, for each value in data_values, whether it's defined or not.
Returns
false iif the end of the container is reached.
template<typename T > bool plDataDescriptor::get_data_row (std::vector< T > & data_row, std::vector< bool > & data_row_def) inline
Get the next data record (row) as an STL vector and advances by one record in the data.
This function make a copy into the two output parameters and is then less efficient than those returning pointers.
Parameters
[out] data_row a vecor of values for all variables described in the record.
[out] data_row_def a vector stating, for each value in data_row, whether it's defined or not.
Returns
false iif the end of the container is reached.
virtual unsigned int plDataDescriptor::get_n_records () virtual
Get the number of records (rows) in the data set.
ATTENTION: For the first call, the default implementation scans the data set and thus has a complexity of O(n) where n is the size.
Returns
the size of the data set.
Reimplemented in plCSVFileDataDescriptor, plMysqlDataDescriptor, plMatrixDataDescriptor< T >, and plODBCDataDescriptor.
Referenced by plMysqlDataDescriptor::get_n_records().
bool plDataDescriptor::get_next_defined_values (plValues & data_values)
Get the defined values from the next data record (row) and advances by one record in the data.
Parameters
[out] data_values an array of values for all variables defined in the record.
Returns
false iif the end of the container is reached.
virtual unsigned int plDataDescriptor::get_num_fields () const pure virtual
Returns the number of fields (columns).
Returns
the number of fields (columns/variables).
Implemented in plCSVFileDataDescriptor, plMysqlDataDescriptor, plMatrixDataDescriptor< T >, plODBCDataDescriptor, and plCSVDataDescriptor.
virtual unsigned int plDataDescriptor::get_simple_stats (std::vector< plFloat > & min_vals, std::vector< plFloat > & max_vals, std::vector< plFloat > & mean_vals, std::vector< plFloat > & stdev_vals, std::vector< unsigned int > & n, unsigned int & ncomplete_rows) virtual
Computes some simple stats on the data.
Parameters
[out] min_vals the minimal value for each data field (column).
[out] max_vals the maximal value for each data field (column).
[out] mean_vals the mean value for each data field (column).
[out] stdev_vals the standard deviation for each data field (column).
[out] n the number of defined records (rows) for each data field (column).
[out] ncomplete_rows the number of complete records (rows) (with no missing values)
Returns
the number of data records (rows)
template<typename T > void plDataDescriptor::get_variable_values (const plSymbol & variable, std::vector< T > & column_vals) inline
Get a column vector.
Parameters
[in] variable the variable of interest.
[out] column_vals the returned column vector.
template<typename T > void plDataDescriptor::get_variable_values (const plSymbol & variable, std::vector< T > & column_vals, std::vector< bool > & column_defs) inline
Get a column vector and the corresponding definition values.
Parameters
[in] variable the variable of interest.
[out] column_vals the returned column vector.
[out] column_defs the corresponding definition values.
bool plDataDescriptor::is_ok () const inline
Returns true if the initialization (construction) is OK.
Returns
true if the initialization (construction) is OK
virtual void plDataDescriptor::Output (std::ostream & out) const protected virtual
Writes the object at the out stream.
Implements plObject.
Reimplemented in plCSVFileDataDescriptor, plMysqlDataDescriptor, plODBCDataDescriptor, plCSVDataDescriptor, and plMatrixDataDescriptor< T >.
virtual std::ostream& plDataDescriptor::print_head (unsigned int n = 20, std::ostream & sout = std::cout, char sep = '\t') virtual
Prints the header and the 'n' first rows in the output stream 'sout'.
This function has as side effect the rewinding of this data descriptor
virtual void plDataDescriptor::print_head (const std::string & file, unsigned int n = 20, char sep = '\t') virtual
Prints the header and the 'n' first rows in the file 'file'.
This function has as side effect the rewinding of this data descriptor
virtual std::ostream& plDataDescriptor::print_simple_stats (std::ostream & sout = std::cout, char sep = '\t') virtual
Prints some simple statistic of the data.
This function has as side effect the rewinding of this data descriptor
virtual void plDataDescriptor::print_simple_stats (const std::string & file, char sep = '\t') virtual
Prints some simple statistic of the data.
This function has as side effect the rewinding of this data descriptor
virtual bool plDataDescriptor::validate (std::vector< unsigned int > & erroneous_lines) virtual
Validate the data set by checking that the provided values are compatible with the types of the given variable conjunction associaded to the data descriptor.
Parameters
[out] erroneous_lines line numbers (starting from 1) in which incompatible values have been found.
Returns
true iff no incompatible values have been found.