ProBT: plComputableObject Class Reference
plComputableObject Class Reference
A computable object on is defined as an abstract object provided with a probability measure function compute().
Public Member Functions
plComputableObject ()
Empty constructor.
plComputableObject (const plComputableObjectList &func_lis)
Creates a conditional or non conditional distribution as a product of a conditional and non conditional distributions.
virtual ~plComputableObject ()
Destroys the function.
plComputableObject (const plComputableObject &)
Copy constructor.
plComputableObject & operator= (const plComputableObject &)
Assignment operator.
plComputableObject & assign_from (const plComputableObject &other)
Same as operator=()
std::string get_print_name () const
Return the distribution print name.
bool is (const plComputableObjectType &type) const
Returns true if the plComputableObject is of type type.
bool is_some_on_signature (const plSignature &prototype_signature) const
Returns true if the plComputableObjectType is at least one of the types described by prototype_signature.
bool is_conditional () const
Returns true if the distribution really is conditional.
bool is_empty () const
Return true if the object is default-constructed (as opposed to full-initialized).
const plSignature & get_signature () const
Get the object full signature (e.g its actual type and parent classes)
plComputableObjectType get_computable_object_type () const
Get the object actual (most derived) type.
plVariablesConjunction get_variables () const
Returns all the variables (left and right) of the computable object.
plVariablesConjunction get_left_variables () const
Returns the left variables of the computable object.
plVariablesConjunction get_right_variables () const
Returns the right variables of the computable object.
plProbValue compute (const plValues &values) const
Computes the value of the function for the input parameter values.
plFloat compute_log (const plValues &values) const
Computes the logarithm value of the function for the input parameter values.
plProbValue compute (const int *values) const
Computes the value of the function for the array input parameter values.
plProbValue compute (const unsigned int *values) const
Computes the value of the function for the array input parameter values.
plProbValue compute (const float *values) const
Computes the value of the function for the array input parameter values.
plProbValue compute (const double *values) const
Computes the value of the function for the array input parameter values.
plFloat compute_log (const int *values) const
Computes the logarithm value of the function for the input parameter values.
plFloat compute_log (const unsigned int *values) const
Computes the logarithm value of the function for the input parameter values.
plFloat compute_log (const float *values) const
Computes the logarithm value of the function for the input parameter values.
plFloat compute_log (const double *values) const
Computes the logarithm value of the function for the input parameter values.
plProbValue compute (const std::vector< int > &parameter) const
Computes the value of the function for the STL vector input parameter 'values'.
plProbValue compute (const std::vector< unsigned int > &parameter) const
Computes the value of the function for the STL vector input parameter 'values'.
plProbValue compute (const std::vector< float > &parameter) const
Computes the value of the function for the STL vector input parameter 'values'.
plProbValue compute (const std::vector< double > &parameter) const
Computes the value of the function for the STL vector input parameter 'values'.
plFloat compute_log (const std::vector< int > &parameter) const
Computes the logarithm value of the function for the input parameter values.
plFloat compute_log (const std::vector< unsigned int > &parameter) const
Computes the logarithm value of the function for the input parameter values.
plFloat compute_log (const std::vector< float > &parameter) const
Computes the logarithm value of the function for the input parameter values.
plFloat compute_log (const std::vector< double > &parameter) const
Computes the logarithm value of the function for the input parameter values.
plComputableObject & rename (const plVariablesConjunction &new_variables)
Renames the head variables of a function and returns a reference to it .
std::ostream & write_head (std::ostream &out=std::cout) const
Writes the the distribution head at the output stream out.
std::string get_head_string () const
Get the distribution head as a string.
std::ostream & write_body (std::ostream &out=std::cout) const
Writes the distribution body at the output stream out.
std::string get_body_string () const
Get the distribution body as a string.
plComputableObjectList operator* (const plComputableObject &f2) const
Concatenation with another computable object operator.
plComputableObjectList concatenate (const plComputableObject &f2) const
Concatenation with another computable object operator.
plComputableObjectList operator* (const plComputableObjectList &v_list) const
Concatenation with a computable objects list operator.
plComputableObjectList concatenate (const plComputableObjectList &v_list) const
Concatenation with a computable objects list operator.
void replace (const plVariablesConjunction &left_vars, const plVariablesConjunction &right_vars, const plComputableObject &new_co)
Replace the referenced distribution P(left_vars | right_vars) by another distribution new_co.
void replace (const plVariablesConjunction &left_vars, const plDistribution &new_distribution)
Replace the distribution P(left_vars) by another distribution new_distribution.
bool operator== (const plComputableObject &other) const
Return true if this and the other object are the same.
bool equal (const plComputableObject &other) const
Return true if this and the other object are the same.
bool operator!= (const plComputableObject &other) const
Return true if this and the other object are not the same.
bool not_equal (const plComputableObject &other) const
Return true if this and the other object are not the same.
bool is_builtin () const
Returns true if and only if the computable object is a ProBT builtin one.
std::ostream & print_evaluation_tree_infos (std::ostream &out) const
Displays the evaluation tree corresponding to the computable object.
long double get_exhaustive_compilation_complexity () const
Get the sum of the number of sums and the number of products required to compile the corresponding expression.
long double get_exhaustive_update_complexity () const
Get the sum of the number of sums and the number of products required to update the corresponding expression for a new given evidence value.
bool is_mutable () const
Get the mutability property.
void tabulate (std::vector< plProbValue > &output) const
Tabulates the computable object in the 'output' vector.
void n_tabulate (std::vector< plProbValue > &output, long unsigned int n) const
Same as tabulate(vector <plProbValue> &output) but using limited sampling iterations n.
void time_tabulate (std::vector< plProbValue > &output, double time_in_seconds) const
Same as tabulate(vector <plProbValue> &output) but using limited sampling time time_in_seconds.
plComputableObjectList get_factors () const
Get the independant factors of a product computable object.
plComputableObjectList get_children () const
Get expression children.
plVariablesConjunction get_marginalized_variables () const
Get expression marginalized variables.
Public Member Functions inherited from plObject
plObject ()
Constructor.
virtual ~plObject ()
Destroys the object.
std::string to_string (std::ostringstream *s=0) const
Returns the object as a string.
Protected Member Functions
virtual void Output (std::ostream &out) const
Writes the object at the output given by "out".
Detailed Description
A computable object on is defined as an abstract object provided with a probability measure function compute().
Constructor & Destructor Documentation
plComputableObject::plComputableObject ()
Empty constructor.
The resulting object is invalid for most operations, except for being assigned to, or used as a return value.
plComputableObject::plComputableObject (const plComputableObjectList & func_lis)
Creates a conditional or non conditional distribution as a product of a conditional and non conditional distributions.
The left variables of the constructed computable object are the concatenation (in the same order) of the left variables of all the terms of the list. Its right variables are the concatenation of the right variables of all the terms and that are not in left one above.
Member Function Documentation
plProbValue plComputableObject::compute (const plValues & values) const
Computes the value of the function for the input parameter values.
ATTENTION: the returned value is guaranteed to be NORMALIZED for and only for:
builtin distributions (basic distributions provided directly by ProBT),
compiled distributions (obtained by using the compile() method).
distributions obtained with instantiate called with parameter ensure_normalization_on_compute = true.
Calling the 'compute' method on distributions resulting from the ask and/or instantiate methods is not guaranteed to return a normalized value unless the instantiate method is called with parameter ensure_normalization_on_compute = true. To be sure to obtain normalized values, consider compiling these distributions using the 'compile' method.
However, this method is useful if you just want to compare the relative magnitudes of several probability values.
plProbValue plComputableObject::compute (const int * values) const
Computes the value of the function for the array input parameter values.
ATTENTION: the returned value is guaranteed to be NORMALIZED for and only for:
builtin distributions (basics distributions provided by ProBT),
compiled distributions (obtained by using the compile method).
distributions obtained with instantiate called with parameter ensure_normalization_on_compute = true.
Calling the compute method on distributions resulting from the ask and/or instantiate methods is not guaranteed to return a normalized value unless the instantiate method is called with parameter ensure_normalization_on_compute = true. To be sure to obtain normalized values, consider compiling these distributions using the 'compile' method.
plProbValue plComputableObject::compute (const unsigned int * values) const
Computes the value of the function for the array input parameter values.
ATTENTION: the returned value is guaranteed to be NORMALIZED for and only for:
builtin distributions (basics distributions provided by ProBT),
compiled distributions (obtained by using the compile method).
distributions obtained with instantiate called with parameter ensure_normalization_on_compute = true.
Calling the compute method on distributions resulting from the ask and/or instantiate methods is not guaranteed to return a normalized value unless the instantiate method is called with parameter ensure_normalization_on_compute = true. To be sure to obtain normalized values, consider compiling these distributions using the 'compile' method.
plProbValue plComputableObject::compute (const float * values) const
Computes the value of the function for the array input parameter values.
ATTENTION: the returned value is guaranteed to be NORMALIZED for and only for:
builtin distributions (basics distributions provided by ProBT),
compiled distributions (obtained by using the compile method).
distributions obtained with instantiate called with parameter ensure_normalization_on_compute = true.
Calling the compute method on distributions resulting from the ask and/or instantiate methods is not guaranteed to return a normalized value unless the instantiate method is called with parameter ensure_normalization_on_compute = true. To be sure to obtain normalized values, consider compiling these distributions using the 'compile' method.
plProbValue plComputableObject::compute (const double * values) const
Computes the value of the function for the array input parameter values.
ATTENTION: the returned value is guaranteed to be NORMALIZED for and only for:
builtin distributions (basics distributions provided by ProBT),
compiled distributions (obtained by using the compile method).
distributions obtained with instantiate called with parameter ensure_normalization_on_compute = true.
Calling the compute method on distributions resulting from the ask and/or instantiate methods is not guaranteed to return a normalized value unless the instantiate method is called with parameter ensure_normalization_on_compute = true. To be sure to obtain normalized values, consider compiling these distributions using the 'compile' method.
plProbValue plComputableObject::compute (const std::vector< int > & parameter) const
Computes the value of the function for the STL vector input parameter 'values'.
ATTENTION: the returned value is guaranteed to be NORMALIZED for and only for:
builtin distributions (basics distributions provided by ProBT),
the compiled distributions (obtained by using the compile method).
distributions obtained with instantiate called with parameter ensure_normalization_on_compute = true.
Calling the 'compute' method on distributions resulting from the ask and/or instantiate methods is not guaranteed to return a normalized value unless the instantiate method is called with parameter ensure_normalization_on_compute = true. To be sure to obtain normalized values, consider compiling these distributions using the compile method.
plProbValue plComputableObject::compute (const std::vector< unsigned int > & parameter) const
Computes the value of the function for the STL vector input parameter 'values'.
ATTENTION: the returned value is guaranteed to be NORMALIZED for and only for:
builtin distributions (basics distributions provided by ProBT),
the compiled distributions (obtained by using the compile method).
distributions obtained with instantiate called with parameter ensure_normalization_on_compute = true.
Calling the 'compute' method on distributions resulting from the ask and/or instantiate methods is not guaranteed to return a normalized value unless the instantiate method is called with parameter ensure_normalization_on_compute = true. To be sure to obtain normalized values, consider compiling these distributions using the compile method.
plProbValue plComputableObject::compute (const std::vector< float > & parameter) const
Computes the value of the function for the STL vector input parameter 'values'.
ATTENTION: the returned value is guaranteed to be NORMALIZED for and only for:
builtin distributions (basics distributions provided by ProBT),
the compiled distributions (obtained by using the compile method).
distributions obtained with instantiate called with parameter ensure_normalization_on_compute = true.
Calling the 'compute' method on distributions resulting from the ask and/or instantiate methods is not guaranteed to return a normalized value unless the instantiate method is called with parameter ensure_normalization_on_compute = true. To be sure to obtain normalized values, consider compiling these distributions using the compile method.
plProbValue plComputableObject::compute (const std::vector< double > & parameter) const
Computes the value of the function for the STL vector input parameter 'values'.
ATTENTION: the returned value is guaranteed to be NORMALIZED for and only for:
builtin distributions (basics distributions provided by ProBT),
the compiled distributions (obtained by using the compile method).
distributions obtained with instantiate called with parameter ensure_normalization_on_compute = true.
Calling the 'compute' method on distributions resulting from the ask and/or instantiate methods is not guaranteed to return a normalized value unless the instantiate method is called with parameter ensure_normalization_on_compute = true. To be sure to obtain normalized values, consider compiling these distributions using the compile method.
bool plComputableObject::equal (const plComputableObject & other) const inline
Return true if this and the other object are the same.
plComputableObjectType plComputableObject::get_computable_object_type () const
Get the object actual (most derived) type.
See Also
get_signature()
long double plComputableObject::get_exhaustive_compilation_complexity () const
Get the sum of the number of sums and the number of products required to compile the corresponding expression.
See Also
get_exhaustive_update_complexity print_evaluation_tree_infos
long double plComputableObject::get_exhaustive_update_complexity () const
Get the sum of the number of sums and the number of products required to update the corresponding expression for a new given evidence value.
See Also
get_exhaustive_compilation_complexity print_evaluation_tree_infos
plVariablesConjunction plComputableObject::get_left_variables () const
Returns the left variables of the computable object.
For instance, for a distribution representing P(A B | C D), this would return A B.
Referenced by plDistributionTable::plDistributionTable().
plVariablesConjunction plComputableObject::get_right_variables () const
Returns the right variables of the computable object.
For instance, for a conditional distribution representing P(A B | C D), this would return C D. This returns an empty plVariablesConjunction for a non-conditional distribution.
Referenced by plDistributionTable::plDistributionTable().
plVariablesConjunction plComputableObject::get_variables () const
Returns all the variables (left and right) of the computable object.
This is equivalent to get_left_variables() ^ get_right_variables().
bool plComputableObject::is_conditional () const
Returns true if the distribution really is conditional.
bool plComputableObject::is_empty () const inline
Return true if the object is default-constructed (as opposed to full-initialized).
bool plComputableObject::is_mutable () const
Get the mutability property.
Returns
'true' if the computable object is mutable.
bool plComputableObject::not_equal (const plComputableObject & other) const inline
Return true if this and the other object are not the same.
bool plComputableObject::operator!= (const plComputableObject & other) const inline
Return true if this and the other object are not the same.
bool plComputableObject::operator== (const plComputableObject & other) const
Return true if this and the other object are the same.
std::ostream& plComputableObject::print_evaluation_tree_infos (std::ostream & out) const
Displays the evaluation tree corresponding to the computable object.
See Also
get_exhaustive_compilation_complexity get_exhaustive_update_complexity
plComputableObject& plComputableObject::rename (const plVariablesConjunction & new_variables)
Renames the head variables of a function and returns a reference to it .
Referenced by plBayesianFilter::get_estimation().
void plComputableObject::replace (const plVariablesConjunction & left_vars, const plVariablesConjunction & right_vars, const plComputableObject & new_co)
Replace the referenced distribution P(left_vars | right_vars) by another distribution new_co.
new_cnd_distribution must have the same left and right variables.
This method is intended to be used especially on non-compiled computable objects such as:
Expressions obtained using the ask method (see plJointDistribution class) and non-conditional expressions obtained using the instantiate method on the conditional expressions above.
Joint distribution objects (plJointDistribution).
Using replace affects only the computable object on which is called. To get a global effect, use mutate instead.
See Also
plMutableComputableObject::mutate
void plComputableObject::replace (const plVariablesConjunction & left_vars, const plDistribution & new_distribution)
Replace the distribution P(left_vars) by another distribution new_distribution.
new_distribution must have the same left variables.
This method is intended to be used especially on non-compiled computable objects such as:
Expressions obtained using the ask method (see plJointDistribution class) and non-conditional expressions obtained using the instantiate method on the conditional expressions above.
Joint distribution objects (plJointDistribution).
Using replace affects only the computable object on which is called. To get a global effect, use mutate instead.
See Also
plMutableComputableObject::mutate
void plComputableObject::tabulate (std::vector< plProbValue > & output) const
Tabulates the computable object in the 'output' vector.
The value is computed for each possible value of the variables and stored in the output vector 'output. Calling this method on computable objects with non-discretized continuous variables throws a plError(27) exception.
In multi-dimensional cases , where and can take, for example, and values respectively, it constructs the probability table on as follows:
output[0] =
output[1] =
.
.
.
output[ ] =
output[ ] =
output[ ] =
.
.
.
output[ ] =
.
.
.
output[ ] =
The same tabulation scheme is used for conditional distributions (eg.,).