ProBT: plExternalFunction Class Reference
plExternalFunction Class Reference
A function defined by the user, generaly used to define a plCndDeterministic.
Public Types
typedef void(* callback_t)(plValues &output_values, const plValues &input_values)
Pointer to a non-member function used as callback for this class.
Public Member Functions
plExternalFunction ()
Default constructor.
virtual ~plExternalFunction ()
Destructor.
plExternalFunction (const plExternalFunction &f)
Copy constructor.
plExternalFunction (const plVariablesConjunction &input_params, callback_t call_function, std::string func_name="")
Defines a user-function with print name func_name where output_params = call_function(input_params), and the callback call_function is a non-member function.
plExternalFunction (const plVariablesConjunction &output_params, const plVariablesConjunction &input_params, callback_t call_function, std::string func_name="")
Defines a user-function with print name func_name where output_params = call_function(input_params), and the callback call_function is a non-member function.
template<class T >
plExternalFunction (const plVariablesConjunction &input_params, T *obj, void(T::*method)(plValues &output_values, const plValues &input_values), std::string func_name="")
Defines a user-function with print name func_name where output_params = obj->method(input_params), and the callback method is a member function.
template<class T >
plExternalFunction (const plVariablesConjunction &input_params, const T *obj, void(T::*method)(plValues &output_values, const plValues &input_values) const, std::string func_name="")
Defines a user-function with print name func_name where output_params = obj->method(input_params), and the callback method is a member function.
template<class T >
plExternalFunction (const plVariablesConjunction &output_params, const plVariablesConjunction &input_params, T *obj, void(T::*method)(plValues &output_values, const plValues &input_values), std::string func_name="")
Defines a user-function with print name func_name where output_params = obj->method(input_params), and the callback method is a member function.
template<class T >
plExternalFunction (const plVariablesConjunction &output_params, const plVariablesConjunction &input_params, const T *obj, void(T::*method)(plValues &output_values, const plValues &input_values) const, std::string func_name="")
Defines a user-function with print name func_name where output_params = obj->method(input_params), and the callback method is a member function.
plExternalFunction & operator= (const plExternalFunction &f)
Assignment operator.
plExternalFunction & assign_from (const plExternalFunction &other)
Same as operator=()
plDataValues operator() (const plValues &values) const
Evaluation operator.
plVariablesConjunction get_variables () const
Returns all the variables (left and right) of the function.
plVariablesConjunction get_left_variables () const
Returns the left variables of the function.
plVariablesConjunction get_right_variables () const
Returns the right variables of the function.
void set_has_side_effect (bool hse)
Set/unset the has_side_effect flag of the function.
bool has_side_effect () const
Return the has_side_effect flag of the function.
const std::string & get_name () const
Get function's name.
Public Member Functions inherited from plObject
plObject ()
Constructor.
virtual ~plObject ()
Destroys the object.
std::string to_string (std::ostringstream *s=0) const
Returns the object as a string.
Static Public Member Functions
static void sum (plValues &the_sum, const plValues &vals)
The Sum function.
static void product (plValues &the_product, const plValues &vals)
The Product function.
static void average (plValues &the_average, const plValues &vals)
The Average function.
static void identity (plValues &the_id, const plValues &vals)
The Identity function.
static void min (plValues &the_min, const plValues &vals)
The Min function.
static void max (plValues &the_max, const plValues &vals)
The Max function.
static void OR (plValues &or_result, const plValues &vals)
The OR function.
static void AND (plValues &and_result, const plValues &vals)
The AND function.
Protected Member Functions
void Output (std::ostream &out) const
Writes the External function at the output given by "out".
Protected Attributes
kplUserFunction * function_at_kernel_
Pointer to the External Function generated at kernel level.
Detailed Description
A function defined by the user, generaly used to define a plCndDeterministic.
It's also used with conditional distributions accepting user functions as a way to fix the known (right) parameters.
Examples of creating and using plExternalFunction can be found in dirac_func_example (deterministic distributions) and in param_func_example (functions as distribution parameters).
Member Typedef Documentation
typedef void(* plExternalFunction::callback_t)(plValues &output_values, const plValues &input_values)
Pointer to a non-member function used as callback for this class.
It takes values for input variables, and fills in values for output variables.
Constructor & Destructor Documentation
plExternalFunction::plExternalFunction ()
Default constructor.
virtual plExternalFunction::~plExternalFunction () virtual
Destructor.
plExternalFunction::plExternalFunction (const plExternalFunction & f)
Copy constructor.
plExternalFunction::plExternalFunction (const plVariablesConjunction & input_params, callback_t call_function, std::string func_name = "")
Defines a user-function with print name func_name where output_params = call_function(input_params), and the callback call_function is a non-member function.
This constructor variant is to be used with conditional parametric forms (the output_params are implicitly defined as the parameter you want to express as a user-function).
plExternalFunction::plExternalFunction (const plVariablesConjunction & output_params, const plVariablesConjunction & input_params, callback_t call_function, std::string func_name = "")
Defines a user-function with print name func_name where output_params = call_function(input_params), and the callback call_function is a non-member function.
This constructor variant is to be used with plCndDeterministic.
template<class T > plExternalFunction::plExternalFunction (const plVariablesConjunction & input_params, T * obj, void(T::*)(plValues &output_values, const plValues &input_values) method, std::string func_name = "") inline
Defines a user-function with print name func_name where output_params = obj->method(input_params), and the callback method is a member function.
This constructor variant is to be used with conditional parametric forms (the output_params are implicitly defined as the parameter you want to express as a user-function).
References plVariablesConjunction::get_variable_list().
template<class T > plExternalFunction::plExternalFunction (const plVariablesConjunction & input_params, const T * obj, void(T::*)(plValues &output_values, const plValues &input_values) const method, std::string func_name = "") inline
Defines a user-function with print name func_name where output_params = obj->method(input_params), and the callback method is a member function.
This constructor variant is to be used with conditional parametric forms (the output_params are implicitly defined as the parameter you want to express as a user-function).
References plVariablesConjunction::get_variable_list().
template<class T > plExternalFunction::plExternalFunction (const plVariablesConjunction & output_params, const plVariablesConjunction & input_params, T * obj, void(T::*)(plValues &output_values, const plValues &input_values) method, std::string func_name = "") inline
Defines a user-function with print name func_name where output_params = obj->method(input_params), and the callback method is a member function.
This constructor variant is to be used with plCndDeterministic.
References plVariablesConjunction::get_variable_list().
template<class T > plExternalFunction::plExternalFunction (const plVariablesConjunction & output_params, const plVariablesConjunction & input_params, const T * obj, void(T::*)(plValues &output_values, const plValues &input_values) const method, std::string func_name = "") inline
Defines a user-function with print name func_name where output_params = obj->method(input_params), and the callback method is a member function.
This constructor variant is to be used with plCndDeterministic.
References plVariablesConjunction::get_variable_list().
Member Function Documentation
plVariablesConjunction plExternalFunction::get_left_variables () const
Returns the left variables of the function.
plVariablesConjunction plExternalFunction::get_right_variables () const
Returns the right variables of the function.
plVariablesConjunction plExternalFunction::get_variables () const
Returns all the variables (left and right) of the function.
This is equivalent to get_left_variables() ^ get_right_variables().
bool plExternalFunction::has_side_effect () const
Return the has_side_effect flag of the function.
See Also
set_has_side_effect
plDataValues plExternalFunction::operator() (const plValues & values) const
Evaluation operator.
plExternalFunction& plExternalFunction::operator= (const plExternalFunction & f)
Assignment operator.
void plExternalFunction::set_has_side_effect (bool hse)
Set/unset the has_side_effect flag of the function.
The has_side_effect flag is used for deciding if distributions using the function are cached or not in the inference process. The default value of this flag is false.
See Also
has_side_effect