ProBT: plCSVDataDescriptor Class Reference
plCSVDataDescriptor Class Reference
A data descriptor for data in CSV (comma-separated values) format.
Public Member Functions
plCSVDataDescriptor (std::string const &file, plVariablesConjunction const &variables=plVariablesConjunction(), bool cache_data=true, bool header_specifies_variables=true)
Constructs a CSV data descriptor over a file containing CSV data.
plCSVDataDescriptor (std::istream &input_stream, plVariablesConjunction const &variables, bool cache_data=true, bool header_specifies_variables=true)
Constructs a CSV data descriptor over an input stream containing CSV data.
void set_field_separators (std::string const &field_separators)
Sets the field separators allowed in the CSV data.
void set_quotes (std::string const &quotes)
Sets the quotes allowed in the CSV data.
void set_undefined_field (std::string const &undefined_field)
Sets the value that will correspond to an undefined field in the CSV data.
void ignore_unknown_variables (bool ignore=true)
When there is a header describing the file variables (header_specifies_variables = true), this lets the parser ignore the unknown variables and their corresponding data columns.
virtual ~plCSVDataDescriptor ()
Destructor.
virtual unsigned int get_num_fields () const
Returns the number of fields in the CSV data.
plVariablesConjunction observed_variables ()
Returns the variables actually present in the CSV file or stream, in order.
virtual bool get_data_record (plValues const *&data_values, const std::vector< bool > *&data_definition)
Get the next data record (row) and advances by one record in the data.
virtual bool get_data_record (std::vector< std::string > &data_values)
Returns the raw, uninterpreted data record as a vector of strings.
virtual void rewind ()
Rewinds the descriptor, by making it restart from the beginning of the data.
Public Member Functions inherited from plDataDescriptor
plDataDescriptor ()
Constructor.
bool is_ok () const
Returns true if the initialization (construction) is OK.
virtual ~plDataDescriptor ()
Destructor.
bool get_data_record_value (plValues &data_values, std::vector< bool > &data_definition)
Get the next data record (row) and advances by one record in the data.
template<typename T >
bool get_data_row (std::vector< T > &data_row, std::vector< bool > &data_row_def)
Get the next data record (row) as an STL vector and advances by one record in the data.
bool get_next_defined_values (plValues &data_values)
Get the defined values from the next data record (row) and advances by one record in the data.
template<typename T >
void get_data_matrix (std::vector< std::vector< T > > &data_matrix, unsigned int n=std::numeric_limits< unsigned int >::max())
Fills the data matrix corresponding to the data container.
template<typename T >
void get_data_matrix (std::vector< std::vector< T > > &data_matrix, std::vector< std::vector< bool > > &def_matrix, unsigned int n=std::numeric_limits< unsigned int >::max())
Fills the data matrix (and the corresponding definition matrix) corresponding to the data container.
virtual void get_data_range (std::vector< plFloat > &min_vals, std::vector< plFloat > &max_vals)
Returns the range of the data.
virtual unsigned int get_simple_stats (std::vector< plFloat > &min_vals, std::vector< plFloat > &max_vals, std::vector< plFloat > &mean_vals, std::vector< plFloat > &stdev_vals, std::vector< unsigned int > &n, unsigned int &ncomplete_rows)
Computes some simple stats on the data.
template<typename T >
void get_column_values (unsigned int n, std::vector< T > &column_vals)
Get a column vector.
template<typename T >
void get_column_values (unsigned int n, std::vector< T > &column_vals, std::vector< bool > &column_defs)
Get a column vector and the corresponding definition values.
template<typename T >
void get_variable_values (const plSymbol &variable, std::vector< T > &column_vals)
Get a column vector.
template<typename T >
void get_variable_values (const plSymbol &variable, std::vector< T > &column_vals, std::vector< bool > &column_defs)
Get a column vector and the corresponding definition values.
virtual bool validate (std::vector< unsigned int > &erroneous_lines)
Validate the data set by checking that the provided values are compatible with the types of the given variable conjunction associaded to the data descriptor.
virtual unsigned int get_n_records ()
Get the number of records (rows) in the data set.
virtual std::ostream & print_head (unsigned int n=20, std::ostream &sout=std::cout, char sep= '\t')
Prints the header and the 'n' first rows in the output stream 'sout'.
virtual void print_head (const std::string &file, unsigned int n=20, char sep= '\t')
Prints the header and the 'n' first rows in the file 'file'.
virtual std::ostream & print_simple_stats (std::ostream &sout=std::cout, char sep= '\t')
Prints some simple statistic of the data.
virtual void print_simple_stats (const std::string &file, char sep= '\t')
Prints some simple statistic of the data.
std::vector< std::vector
< plFloat > > use_for_discretization (const std::vector< plVariableDiscretizer * > &discretizers, const std::vector< size_t > &variable_columns)
Return the discretization intervals for the variables corresponding to columns variable_columns according to this data set.
std::vector< plFloat > use_for_discretization (plVariableDiscretizer *discretizer, size_t variable_column)
Return the discretization intervals for the variable corresponding to column variable_column according to this data set.
Public Member Functions inherited from plObject
plObject ()
Constructor.
virtual ~plObject ()
Destroys the object.
std::string to_string (std::ostringstream *s=0) const
Returns the object as a string.
Public Member Functions inherited from plStringDataDescriptor
plVariablesConjunction guess_variables (bool header, int real_discretization=-1)
Tries to guess the variables described by a string data descriptor, by examining its data.
Static Public Member Functions
static plVariablesConjunction guess_variables (std::string const &csv_file, bool header=true, int real_discretization=-1)
Tries to guess the variables described in a CSV file, by parsing it.
Protected Member Functions
virtual void Output (std::ostream &os) const
Output a human-readable representation of the descriptor.
Detailed Description
A data descriptor for data in CSV (comma-separated values) format.
It can parse the data from a file or a file descriptor. It is slower than plCSVFileDataDescriptor. However, it is safer (it will detect and report parse errors), and may be easier to use:
by default, it allows several common CSV syntaxes
it allows to specify the variables and order of the columns inside the file
it allows using an input stream instead of a file.
It is based on RFC 4180: http://tools.ietf.org/html/rfc4180, with the following extensions:
records are ended/separated by either CR, LF, CRLF, or any sequence of mixed CR and LF
empty lines are skipped
leading and trailing spaces and tabulations around a quoted field are ignored
each field can be quoted with either " (double quote) or ' (single quote) (customisable using set_quotes())
fields can be separated with either , (comma) or ; (semicolon) (customisable using set_field_separators())
an empty field is considered undefined
additionally, a field equal to " " (one space) is also considered undefined (customisable using set_undefined_field()).
Constructor & Destructor Documentation
plCSVDataDescriptor::plCSVDataDescriptor (std::string const & file, plVariablesConjunction const & variables = plVariablesConjunction(), bool cache_data = true, bool header_specifies_variables = true)
Constructs a CSV data descriptor over a file containing CSV data.
Parameters
[in] file The name of the file containing the CSV data. The file must exist and be readable.
[in] variables A conjunction describing the variables described in the file.
If header_specifies_variables is false, this should be the exact ordered list of variables present in the file. get_data_record() will return values for all these variables.
If header_specifies_variables is true, by default, this should be a superset of the variables announced in the file header. get_data_record() will return values for the variables present in the file header.
If header_specifies_variables is true and you called ignore_unknown_variables(), get_data_record() will return values for variables that are both in this parameter and in the file header (that is to say, the intersection of these two sets).
[in] cache_data Whether this descriptor should cache the data, in order to avoid parsing after the first rewind(). If memory allows it, this provides a significant speed boost when several passes are made over the data.
[in] header_specifies_variables Whether the first line of the file contains a header listing the names of the variables present in the file (in order). This header allows having superfluous values in the CSV data, and reordering the variables in the data.
plCSVDataDescriptor::plCSVDataDescriptor (std::istream & input_stream, plVariablesConjunction const & variables, bool cache_data = true, bool header_specifies_variables = true)
Constructs a CSV data descriptor over an input stream containing CSV data.
Parameters
input_stream The input stream containing the CSV data.
variables A conjunction containing a superset of the variables described in the stream. All variables in this conjunction must have different names. If header_specifies_variables is false, this must correspond exactly to the variables specified in the CSV data.
cache_data Whether this descriptor should cache the data, in order to avoid parsing after the first rewind(). If memory allows it, this provides a significant speed boost when several passes are made over the data.
header_specifies_variables Whether the first line of the file contains a header listing the names of the variables present in the file (in order). This header allows having superfluous values in the CSV data, and reordering the variables in the data.
Member Function Documentation
virtual bool plCSVDataDescriptor::get_data_record (plValues const *& data_values, const std::vector< bool > *& data_definition) virtual
Get the next data record (row) and advances by one record in the data.
Parameters
[out] data_values a pointer to a plValues containing assignments for all variables described in the record.
[out] data_definition a vector stating, for each value in data_values, whether it's defined or not.
Returns
false iif the end of the container is reached.
The returned pointers are managed internally: you should not attempt to delete them, or use them after another call to get_data_record(). Also, you should not use them when get_data_record() returns false.
This method triggers parsing of the file or stream. Therefore, you should make sure to call set_quotes(), set_field_separators(), set_undefined_field() or ignore_unknown_variables() (if necessary) before calling this method.
Implements plDataDescriptor.
virtual bool plCSVDataDescriptor::get_data_record (std::vector< std::string > & data_values) virtual
Returns the raw, uninterpreted data record as a vector of strings.
Parameters
[out] data_values Record element, resized as needed and filled in by this method.
Returns
false iff the end of the container is reached.
This method consumes one line of CVS input.
This method triggers parsing of the file or stream. Therefore, you should make sure to call set_quotes() or set_field_separators() (if necessary) before calling this method. Methods set_undefined_field() and ignore_unknown_variables() have no effect on what this methods returns.
Warning: when the cache is enabled, there are important rules to follow to avoid losing data:
after calling this method, you should always call rewind() before calling get_data_record(plValues const * & data_values, data_definition)
once you have called get_data_record(plValues const * & data_values, data_definition) once, you should not call this method anymore, even after doing a rewind().
There are no such restrictions when the descriptor's cache is disabled.
Implements plStringDataDescriptor.
static plVariablesConjunction plCSVDataDescriptor::guess_variables (std::string const & csv_file, bool header = true, int real_discretization = -1) inline static
Tries to guess the variables described in a CSV file, by parsing it.
Parameters
[in] csv_file Name of the CSV file.
[in] header Whether the CSV file contains a header describing the variable names.
[in] real_discretization Discretization to apply to real variables (treated as plContinuousIntervalType). A negative value prescribes no discretization: plRealType is used.
Returns
A conjunction of variables corresponding to the variables in the CSV file.
References guess_variables(), and ignore_unknown_variables().
Referenced by guess_variables().
void plCSVDataDescriptor::ignore_unknown_variables (bool ignore = true)
When there is a header describing the file variables (header_specifies_variables = true), this lets the parser ignore the unknown variables and their corresponding data columns.
The "known" variables are those that were passed to the constructor.
By default, unknown variables trigger an exception when parsing the header.
When the file header is not used (header_specifies_variables = false), this has no effect.
Calling this method once the file header has already been parsed has no effect.
Referenced by guess_variables().
plVariablesConjunction plCSVDataDescriptor::observed_variables () virtual
Returns the variables actually present in the CSV file or stream, in order.
If header_specifies_variables was false at construction time, this returns the variables passed to the constructor.
If header_specifies_variables was true at construction, this corresponds to the data header. Therefore, this triggers parsing of the file or stream. In this case, you should make sure to call set_quotes(), set_field_separators(), set_undefined_field() or ignore_unknown_variables() (if necessary) before calling this method.
Implements plDataDescriptor.
virtual void plCSVDataDescriptor::rewind () virtual
Rewinds the descriptor, by making it restart from the beginning of the data.
This is always possible for a descriptor attached to a file. For a descriptor attached to a stream, this will work if the descriptor is cached; if it is not cached, an error will be raised (since there is no way to rewind an input stream).
Implements plDataDescriptor.
void plCSVDataDescriptor::set_field_separators (std::string const & field_separators)
Sets the field separators allowed in the CSV data.
Any character of the passed string will be accepted as a field separator. Note that a field separator cannot be made of several consecutive characters.
The default value is ",;".
void plCSVDataDescriptor::set_quotes (std::string const & quotes)
Sets the quotes allowed in the CSV data.
Any character of the passed string will be accepted as a quoting character. Note that there is no way to use different starting and ending characters for a quote, or a multi-character quote.
The default value is "\"'": single and double quotes.
void plCSVDataDescriptor::set_undefined_field (std::string const & undefined_field)
Sets the value that will correspond to an undefined field in the CSV data.
Note that there is no way to specify several possible values for an undefined field.
In addition to this value, an empty field always corresponds to an undefined field.
The default value is " ": a string of exactly one space.