ProBT: plStatFunctions Class Reference
plStatFunctions Class Reference
Statistics utility functions.
Static Public Member Functions
static plFloat erf (plFloat x)
Erf function.
static plFloat normal_pdf (plFloat x, plFloat mu=0.0, plFloat sigma=1.0)
Normal Probability Density Function (pdf).
static plFloat phi (plFloat x)
Phi is the Cumulative (repartition) Distribution Function (cdf) of the stantard normal (Gaussian) distribution: Phi(x) = 0.5 + 0.5 * erf(x/sqrt(2)).
static plFloat inv_phi (plFloat u)
The inverse of the Phi function above.
static plFloat log_multinomial_beta (const std::vector< plFloat > &x)
Log Multinomial Beta function.
static plFloat multinomial_beta (const std::vector< plFloat > &x)
Multinomial Beta function.
static plFloat log_beta (plFloat x, plFloat y)
Log Beta function.
static plFloat beta (plFloat x, plFloat y)
Beta function.
static plFloat log_gamma (plFloat x)
Log-Gamma function.
static plFloat gamma (plFloat x)
Gamma function.
static plFloat incomplete_gamma (plFloat a, plFloat x)
Incomplete Gamma integral.
static plFloat incomplete_gamma_c (plFloat a, plFloat x)
Complemented incomplete Gamma integral.
static plFloat log_factorial (unsigned int n)
Return the log of n!.
static plFloat factorial (unsigned int n)
Return n!.
Detailed Description
Statistics utility functions.
Member Function Documentation
static plFloat plStatFunctions::beta (plFloat x, plFloat y) inline static
Beta function.
References plBetaFunction().
static plFloat plStatFunctions::erf (plFloat x) inline static
Erf function.
References plErf().
static plFloat plStatFunctions::factorial (unsigned int n) inline static
Return n!.
References plFactorial().
static plFloat plStatFunctions::gamma (plFloat x) inline static
Gamma function.
References plGammaFunc().
static plFloat plStatFunctions::incomplete_gamma (plFloat a, plFloat x) inline static
Incomplete Gamma integral.
The function is defined by:
See Also
incomplete_gamma_c
References plIncompleteGammaFunc().
static plFloat plStatFunctions::incomplete_gamma_c (plFloat a, plFloat x) inline static
Complemented incomplete Gamma integral.
The function is defined by:
See Also
incomplete_gamma
References plIncompleteGammaCFunc().
static plFloat plStatFunctions::inv_phi (plFloat u) inline static
The inverse of the Phi function above.
References plInvPhi().
static plFloat plStatFunctions::log_beta (plFloat x, plFloat y) inline static
Log Beta function.
References plLogBetaFunction().
static plFloat plStatFunctions::log_factorial (unsigned int n) inline static
Return the log of n!.
References plLogFactorial().
static plFloat plStatFunctions::log_gamma (plFloat x) inline static
Log-Gamma function.
References plLgamma().
static plFloat plStatFunctions::log_multinomial_beta (const std::vector< plFloat > & x) inline static
Log Multinomial Beta function.
References plLogMultinomialBeta().
static plFloat plStatFunctions::multinomial_beta (const std::vector< plFloat > & x) inline static
Multinomial Beta function.
References plMultinomialBeta().
static plFloat plStatFunctions::normal_pdf (plFloat x, plFloat mu = 0.0, plFloat sigma = 1.0) inline static
Normal Probability Density Function (pdf).