ProBT: plRandom Class Reference
plRandom Class Reference
Basic random number generation utility functions.
Static Public Member Functions
static void seed (int seed_value)
Seed the random generator.
static unsigned int uniform_integer (unsigned int max)
Draw uniformly an integer random value in the range [0,max-1].
static plFloat uniform_float (plFloat max)
Draw uniformly a floating number random value in the range [0,max[.
static plFloat normal_float (plFloat m, plFloat sd)
Draw a floating number random value normally distributed widh m as mean and sd as standard deviation.
static plFloat normal_float (plFloat m, plFloat sd, plFloat a, plFloat b)
Draw a floating number random value normally distributed widh m as mean and sd as standard deviation in the range [a,b[.
template<typename T >
static unsigned long draw_using_repartition (unsigned long size, const T *repartition)
Return a random index drawn from the distribution corresponding to the repartition function (table) repartition.
template<typename T >
static unsigned long draw_using_repartition (const std::vector< T > &repartition)
Return a random index drawn from the distribution corresponding to the repartition function (table) repartition.
Detailed Description
Basic random number generation utility functions.
Member Function Documentation
static plFloat plRandom::normal_float (plFloat m, plFloat sd) inline static
Draw a floating number random value normally distributed widh m as mean and sd as standard deviation.
It uses the Box-Muller algorithm and is based on the MT1937 uniform random generator.
References plNormalRandom().
static plFloat plRandom::normal_float (plFloat m, plFloat sd, plFloat a, plFloat b) inline static
Draw a floating number random value normally distributed widh m as mean and sd as standard deviation in the range [a,b[.
It uses the Box-Muller algorithm and is based on the MT1937 uniform random generator.
References plNormalRandom().
static plFloat plRandom::uniform_float (plFloat max) inline static
Draw uniformly a floating number random value in the range [0,max[.
It uses the MT1937 random generator.
References plRandomFloat().
static unsigned int plRandom::uniform_integer (unsigned int max) inline static
Draw uniformly an integer random value in the range [0,max-1].
It uses the MT1937 random generator.
References plRandomInt().