ProBT: plMysqlDataDescriptor Class Reference
plMysqlDataDescriptor Class Reference
This class implements a data descriptor for Mysql databases.
Public Member Functions
plMysqlDataDescriptor (const plVariablesConjunction &variables, const std::string &host, const std::string &user, const std::string &passwd, const std::string &db, const std::string &query, bool cache_data=true, unsigned int port=0, const std::string &unix_socket="", unsigned long client_flag=0)
Constructor using database parameters and associating it to a set of variables.
plMysqlDataDescriptor (const std::string &host, const std::string &user, const std::string &passwd, const std::string &db, const std::string &query, bool cache_data=true, unsigned int port=0, const std::string &unix_socket="", unsigned long client_flag=0)
Constructor using database parameters without associating it to a set of variables.
plMysqlDataDescriptor (const plVariablesConjunction &variables, MYSQL *mysql_db_connection, const std::string &query, bool cache_data=true)
Constructor using an already open connection and associating it to a set of variables.
plMysqlDataDescriptor (MYSQL *mysql_db_connection, const std::string &query, bool cache_data=true)
Constructor using an already open connection without associating it to a set of variables.
~plMysqlDataDescriptor ()
Destructor.
void rewind ()
Rewinds the container to go back to its begining.
bool get_data_record (const plValues *&data_values, const std::vector< bool > *&data_definition)
Get the next data record (row) and advances by one record in the data.
unsigned int get_num_fields () const
Returns the number of fields (columns).
virtual unsigned int get_n_records ()
Get the number of records (rows) in the data set.
void set_variables (const plVariablesConjunction &variables)
Set the variables to be associated to the data descriptor.
virtual plVariablesConjunction observed_variables ()
Get the variables associated to the descriptor.
Public Member Functions inherited from plDataDescriptor
plDataDescriptor ()
Constructor.
bool is_ok () const
Returns true if the initialization (construction) is OK.
virtual ~plDataDescriptor ()
Destructor.
bool get_data_record_value (plValues &data_values, std::vector< bool > &data_definition)
Get the next data record (row) and advances by one record in the data.
template<typename T >
bool get_data_row (std::vector< T > &data_row, std::vector< bool > &data_row_def)
Get the next data record (row) as an STL vector and advances by one record in the data.
bool get_next_defined_values (plValues &data_values)
Get the defined values from the next data record (row) and advances by one record in the data.
template<typename T >
void get_data_matrix (std::vector< std::vector< T > > &data_matrix, unsigned int n=std::numeric_limits< unsigned int >::max())
Fills the data matrix corresponding to the data container.
template<typename T >
void get_data_matrix (std::vector< std::vector< T > > &data_matrix, std::vector< std::vector< bool > > &def_matrix, unsigned int n=std::numeric_limits< unsigned int >::max())
Fills the data matrix (and the corresponding definition matrix) corresponding to the data container.
virtual void get_data_range (std::vector< plFloat > &min_vals, std::vector< plFloat > &max_vals)
Returns the range of the data.
virtual unsigned int get_simple_stats (std::vector< plFloat > &min_vals, std::vector< plFloat > &max_vals, std::vector< plFloat > &mean_vals, std::vector< plFloat > &stdev_vals, std::vector< unsigned int > &n, unsigned int &ncomplete_rows)
Computes some simple stats on the data.
template<typename T >
void get_column_values (unsigned int n, std::vector< T > &column_vals)
Get a column vector.
template<typename T >
void get_column_values (unsigned int n, std::vector< T > &column_vals, std::vector< bool > &column_defs)
Get a column vector and the corresponding definition values.
template<typename T >
void get_variable_values (const plSymbol &variable, std::vector< T > &column_vals)
Get a column vector.
template<typename T >
void get_variable_values (const plSymbol &variable, std::vector< T > &column_vals, std::vector< bool > &column_defs)
Get a column vector and the corresponding definition values.
virtual bool validate (std::vector< unsigned int > &erroneous_lines)
Validate the data set by checking that the provided values are compatible with the types of the given variable conjunction associaded to the data descriptor.
virtual std::ostream & print_head (unsigned int n=20, std::ostream &sout=std::cout, char sep= '\t')
Prints the header and the 'n' first rows in the output stream 'sout'.
virtual void print_head (const std::string &file, unsigned int n=20, char sep= '\t')
Prints the header and the 'n' first rows in the file 'file'.
virtual std::ostream & print_simple_stats (std::ostream &sout=std::cout, char sep= '\t')
Prints some simple statistic of the data.
virtual void print_simple_stats (const std::string &file, char sep= '\t')
Prints some simple statistic of the data.
std::vector< std::vector
< plFloat > > use_for_discretization (const std::vector< plVariableDiscretizer * > &discretizers, const std::vector< size_t > &variable_columns)
Return the discretization intervals for the variables corresponding to columns variable_columns according to this data set.
std::vector< plFloat > use_for_discretization (plVariableDiscretizer *discretizer, size_t variable_column)
Return the discretization intervals for the variable corresponding to column variable_column according to this data set.
Public Member Functions inherited from plObject
plObject ()
Constructor.
virtual ~plObject ()
Destroys the object.
std::string to_string (std::ostringstream *s=0) const
Returns the object as a string.
Protected Member Functions
virtual void Output (std::ostream &os) const
Writes the object at the out stream.
Detailed Description
This class implements a data descriptor for Mysql databases.
Constructor & Destructor Documentation
plMysqlDataDescriptor::plMysqlDataDescriptor (const plVariablesConjunction & variables, const std::string & host, const std::string & user, const std::string & passwd, const std::string & db, const std::string & query, bool cache_data = true, unsigned int port = 0, const std::string & unix_socket = "", unsigned long client_flag = 0) inline
Constructor using database parameters and associating it to a set of variables.
Parameters
[in] variables The set of variables to be associated to the descriptor.
[in] host Host name (address).
[in] user Mysql user name.
[in] passwd User's password.
[in] db Database name.
[in] query The query to execute.
[in] cache_data true if we want to store the data in client's memory.
[in] port Port number (use the default parameter's value when possible).
[in] unix_socket The path to the used unix socket (use the default parameter's value when possible).
[in] client_flag Connection client flag (use the default parameter's value when possible).
References PL_NO_ERROR, and set_variables().
plMysqlDataDescriptor::plMysqlDataDescriptor (const std::string & host, const std::string & user, const std::string & passwd, const std::string & db, const std::string & query, bool cache_data = true, unsigned int port = 0, const std::string & unix_socket = "", unsigned long client_flag = 0) inline
Constructor using database parameters without associating it to a set of variables.
The actual association to a set of variables could be done later by calling set_variables().
Parameters
[in] host Host name (address).
[in] user Mysql user name.
[in] passwd User's password.
[in] db Database name.
[in] query The query to execute.
[in] cache_data true if we want to store the data in client's memory.
[in] port Port number (use the default parameter's value when possible).
[in] unix_socket The path to the used unix socket (use the default parameter's value when possible).
[in] client_flag Connection client flag (use the default parameter's value when possible).
References PL_NO_ERROR.
plMysqlDataDescriptor::plMysqlDataDescriptor (const plVariablesConjunction & variables, MYSQL * mysql_db_connection, const std::string & query, bool cache_data = true) inline
Constructor using an already open connection and associating it to a set of variables.
Parameters
[in] variables The set of variables to be associated to the descriptor.
[in,out] mysql_db_connection An already open connection.
[in] query The query to execute.
[in] cache_data true if we want to store the data in client's memory.
References PL_NO_ERROR, and set_variables().
plMysqlDataDescriptor::plMysqlDataDescriptor (MYSQL * mysql_db_connection, const std::string & query, bool cache_data = true) inline
Constructor using an already open connection without associating it to a set of variables.
The actual association to a set of variables could be done later by calling set_variables().
Parameters
[in,out] mysql_db_connection An already open connection.
[in] query The query to execute.
[in] cache_data true if we want to store the data in client's memory.
References PL_NO_ERROR.
Member Function Documentation
bool plMysqlDataDescriptor::get_data_record (const plValues *& data_values, const std::vector< bool > *& data_definition) inline virtual
Get the next data record (row) and advances by one record in the data.
Parameters
[out] data_values an array of values for all variables described in the record.
[out] data_definition a vector stating, for each value in data_values, whether it's defined or not.
Returns
false iif the end of the container is reached.
The returned pointers are managed internally: you should not attempt to delete them, or use them after another call to get_data_record(). Also, you should not use them when get_data_record() returns false.
Implements plDataDescriptor.
References plValues::size().
virtual unsigned int plMysqlDataDescriptor::get_n_records () inline virtual
Get the number of records (rows) in the data set.
ATTENTION: if not cached, the first call scans the data set and thus has a complexity of O(n) where n is the size.
Returns
the size of the data set.
Reimplemented from plDataDescriptor.
References plDataDescriptor::get_n_records().
unsigned int plMysqlDataDescriptor::get_num_fields () const inline virtual
Returns the number of fields (columns).
Returns
the number of fields (columns/variables).
Implements plDataDescriptor.
Referenced by set_variables().
virtual void plMysqlDataDescriptor::Output (std::ostream & out) const inline protected virtual
Writes the object at the out stream.
Reimplemented from plDataDescriptor.
void plMysqlDataDescriptor::set_variables (const plVariablesConjunction & variables) inline
Set the variables to be associated to the data descriptor.
This method is to be called when the descriptor is constructed without providing the variables list. After this call, observed_variables() will return the passed 'variables' parameter.
Parameters
[in] variables The variables to be associated to the data descriptor
References plVariablesConjunction::dim(), get_num_fields(), plVariablesConjunction::get_type(), plVariablesConjunction::get_var_type(), plVariablesConjunction::is_empty(), and PL_LABEL.
Referenced by plMysqlDataDescriptor().