ProBT: plLearnObject Class Reference
plLearnObject Class Reference abstract
This is the base class of all incremental (adaptive) learning objects.
Public Member Functions
plLearnObject (const plVariablesConjunction &variables)
Constructor using a set of variables.
plLearnObject ()
Default constructor.
plLearnObject (const plLearnObject &obj)
Copy constructor.
plLearnObject & operator= (const plLearnObject &obj)
Assignment operator.
virtual ~plLearnObject ()
Destructor.
unsigned int get_nsamples () const
Returns the number of the points used in learning (i.e.
plFloat get_total_weight () const
Returns the sum of weights of the points used in learning (i.e.
virtual void get_total_weight (std::vector< plFloat > &w) const
Returns the sum of weights of the points used in learning (i.e.
virtual void reset ()
Resets learning (forgets all learned data).
virtual plComputableObject get_computable_object () const =0
Constructs the computable object corresponding to the learnt distribution.
bool add_point (const plValues &point, plFloat weight=PL_ONE)
Adds a data point with a given weight.
bool add_point (const int *point, plFloat weight=PL_ONE)
Adds a multidimensional data point with a given weight.
bool add_point (const std::vector< int > &point, plFloat weight=PL_ONE)
Adds a multidimensional data point with a given weight.
bool add_point (int point, plFloat weight=PL_ONE)
Adds a unidimensional data point with a given weight.
bool add_point (const plValues &point, const std::vector< bool > &is_defined, plFloat weight=PL_ONE)
Adds a multidimensional data point with a given weight; the components of the point are specified in non-contiguously.
bool add_point (const int *point, const std::vector< bool > &is_defined, plFloat weight=PL_ONE)
Adds a multidimensional data point with a given weight; the components of the point are specified in order but non-contiguously.
bool add_point (const std::vector< int > &point, const std::vector< bool > &is_defined, plFloat weight=PL_ONE)
Adds a multidimensional data point with a given weight; the components of the point are specified in order but non-contiguously.
int learn (plDataDescriptor &data_descriptor, unsigned int n=std::numeric_limits< unsigned int >::max())
Learn using the data set defined by the container 'data_descriptor'.
int learn (plDataDescriptor &data_descriptor, plVariablesConjunction const &variables, bool rewind_before_use=true)
Deprecated method, kept temporarily for compatibility purposes.
void learn (const std::vector< int > &vals)
Learn using a set of one-dimensional values.
void learn (const std::vector< int > &vals, const std::vector< bool > &def)
Learn using a set of one-dimensional values with their definition information.
virtual const
plVariablesConjunction & get_left_variables () const =0
Returns the left variables.
virtual const
plVariablesConjunction & get_right_variables () const =0
Returns the right variables.
const plVariablesConjunction & get_variables () const
Returns all variables.
virtual unsigned int get_n_parameters () const =0
Returns the ACTUAL number of parameters.
virtual plLearnObject * clone () const =0
Clone the learning object.
Public Member Functions inherited from plObject
plObject ()
Constructor.
virtual ~plObject ()
Destroys the object.
std::string to_string (std::ostringstream *s=0) const
Returns the object as a string.
Additional Inherited Members
Static Public Member Functions inherited from plLearner
static plJointDistribution learn_model_parameters (const std::vector< plLearnObject * > &learn_objects, plDataDescriptor &data_descriptor)
Learns the parameters of a model.
static plJointDistribution learn_model_parameters (const std::vector< plLearnObject * > &learn_objects, const plComputableObjectList &init_distribs, plDataDescriptor &data_descriptor)
Learns the parameters of a model.
Protected Member Functions inherited from plObject
virtual void Output (std::ostream &out) const =0
Writes the object at the out stream.
Detailed Description
This is the base class of all incremental (adaptive) learning objects.
Constructor & Destructor Documentation
plLearnObject::plLearnObject (const plVariablesConjunction & variables) explicit
Constructor using a set of variables.
plLearnObject::plLearnObject () inline
Default constructor.
Member Function Documentation
bool plLearnObject::add_point (const plValues & point, plFloat weight = PL_ONE) inline
Adds a data point with a given weight.
Parameters
[in] point Data point to add.
[in] weight Weight of the added point. If weight is an integer, add_point(x, weight) is equivalent to doing weight times add_point(x).
Returns
True if and only if the point could be added.
bool plLearnObject::add_point (const int * point, plFloat weight = PL_ONE) inline
Adds a multidimensional data point with a given weight.
Parameters
[in] point Data point to add, as a C array.
[in] weight Weight of the added point. If weight is an integer, add_point(x, weight) is equivalent to doing weight times add_point(x).
Returns
True if and only if the point could be added.
bool plLearnObject::add_point (const std::vector< int > & point, plFloat weight = PL_ONE) inline
Adds a multidimensional data point with a given weight.
Parameters
[in] point Data point to add, as an STL vector.
[in] weight Weight of the added point. If weight is an integer, add_point(x, weight) is equivalent to doing weight times add_point(x).
Returns
True if and only if the point could be added.
bool plLearnObject::add_point (int point, plFloat weight = PL_ONE) inline
Adds a unidimensional data point with a given weight.
Parameters
[in] point Data point to add. It must be convertible to the type of data of the variable.
[in] weight Weight of the added point. If weight is an integer, add_point(x, weight) is equivalent to doing weight times add_point(x).
Returns
True if and only if the point could be added.
bool plLearnObject::add_point (const plValues & point, const std::vector< bool > & is_defined, plFloat weight = PL_ONE) inline
Adds a multidimensional data point with a given weight; the components of the point are specified in non-contiguously.
Parameters
[in] point Data point to add, as a plValues.
[in] is_defined Indicates which components should be used for learning. is_defined[i] should be true if and only if point[i] is to be used.
[in] weight Weight of the added point. If weight is an integer, add_point(x, weight) is equivalent to doing weight times add_point(x).
Returns
True if and only if the point could be added.
bool plLearnObject::add_point (const int * point, const std::vector< bool > & is_defined, plFloat weight = PL_ONE) inline
Adds a multidimensional data point with a given weight; the components of the point are specified in order but non-contiguously.
Parameters
[in] point Data point to add, as a C array.
[in] is_defined Indicates which components should be used for learning. is_defined[i] should be true if and only if point[i] is to be used.
[in] weight Weight of the added point. If weight is an integer, add_point(x, weight) is equivalent to doing weight times add_point(x).
Returns
True if and only if the point could be added.
bool plLearnObject::add_point (const std::vector< int > & point, const std::vector< bool > & is_defined, plFloat weight = PL_ONE) inline
Adds a multidimensional data point with a given weight; the components of the point are specified in order but non-contiguously.
Parameters
[in] point Data point to add, as an STL vector.
[in] is_defined Indicates which components should be used for learning. is_defined[i] should be true if and only if point[i] is to be used.
[in] weight Weight of the added point. If weight is an integer, add_point(x, weight) is equivalent to doing weight times add_point(x).
Returns
True if and only if the point could be added.
virtual plComputableObject plLearnObject::get_computable_object () const pure virtual
Constructs the computable object corresponding to the learnt distribution.
Constructs and returns the computable object (conditional or non conditional distribution) corresponding to the current state of this learner
Implemented in plLearnFrozenDistribution, plLearnDistribVector, plLearnCndObject, and plNonCndLearnObject.
Referenced by plLearnFrozenDistribution::Output().
virtual unsigned int plLearnObject::get_n_parameters () const pure virtual
Returns the ACTUAL number of parameters.
It could be different from the number of parameters returned by get_parameters.
For example, the actual number of parameters of a N dimensional normal distribution is N + N*(N+1)/2 because the covariance matrix is symmetric.
Implemented in plLearnFrozenDistribution, plLearnDistribVector, plBayesLearnLogNormalWithKnownShape, plBayesLearnNdNormalWithKnownVariance, plLearnHistogram, plBayesLearn1dNormalWithKnownMean, plBayesLearnExponential, plLearnNoisyOR, plBayesLearnProbTable, plBayesLearnBinomial, plLearnDistributionTable, plBayesLearn1dNormalWithKnownStandardDeviation, plLearn1dNormal, plLearnSoftmax, plBayesLearnGamma, plBayesLearnPoisson, plLearnMixtureModel, plLearnNdNormal, plLearnExponential, plLearnPoisson, plLearnLinearRegression, plLearnBeta, plLearnLogNormal, plLearnSoftmaxFamily, plLearnLinearRegressionFamily, plLearnGamma, and plLearnSparseHistogram.
unsigned int plLearnObject::get_nsamples () const inline
Returns the number of the points used in learning (i.e.
added using the add_point methods).
plFloat plLearnObject::get_total_weight () const inline
Returns the sum of weights of the points used in learning (i.e.
added using add_point()).
virtual void plLearnObject::get_total_weight (std::vector< plFloat > & w) const inline virtual
Returns the sum of weights of the points used in learning (i.e.
added using the add_point methods).
Reimplemented in plLearnDistribVector.
int plLearnObject::learn (plDataDescriptor & data_descriptor, unsigned int n = std::numeric_limits< unsigned int >::max())
Learn using the data set defined by the container 'data_descriptor'.
Parameters
[in] data_descriptor the data set to be used.
[in] n the number of data rows to be used.
Returns
the number of the inserted points on success. Returns a negative value if the data descriptor is not OK (eg, CSV file does not exist, mysql server is not responding,...).
It is the responsibility of the caller to setup the data descriptor properly before calling this method, for instance by calling rewind() on it if necessary. Also, this method does not attempt to rewind() the data descriptor before returning.
int plLearnObject::learn (plDataDescriptor & data_descriptor, plVariablesConjunction const & variables, bool rewind_before_use = true) inline
Deprecated method, kept temporarily for compatibility purposes.
Identical in function to the above learn().
Parameters
[in] data_descriptor The data set to use for learning.
[in] variables Variables in the data set. This should be equal to data_descriptor.observed_variables().
[in] rewind_before_use Whether the method should rewind the data descriptor before using it.
References plDataDescriptor::observed_variables(), plDataDescriptor::rewind(), and plError::warn().