ProBT: plVariablesConjunction Class Reference
plVariablesConjunction Class Reference
The plVariablesConjunction class implements the conjunction of a set of variables.
Public Types
typedef
plVariablesConjunction_const_iterator const_iterator
Associated const_iterator.
Public Member Functions
const kplVariableList & get_variable_list () const
Needed by the Python bindings, but not part of the user API.
plVariablesConjunction ()
Default constructor, creates an empty variable conjuction.
virtual ~plVariablesConjunction ()
Destructor, if the variable represents a list erase the list but not the variables on the list.
plVariablesConjunction operator^ (const plVariablesConjunction &variable) const
Return the concatenation of the variable var (at right side of the operator) with the variable at left side.
plVariablesConjunction concatenate (const plVariablesConjunction &variable) const
Return the concatenation of the variable var (at right side of the operator) with the variable at left side.
long double cardinality () const
Returns the number of values taken by the variable conjunction.
bool is_discretized () const
Returns true if the conjunction contains only discretizable symbols (ie, all types excluding non-discretized plRealType), false otherwise.
bool is_discrete () const
Returns true if the conjunction contains only discrete symbols, false otherwise.
bool is_continuous () const
Returns true if the conjunction contains only continuous symbols (ie, plRealType or plContinuousIntervalType), false otherwise.
size_t dim () const
Returns the number of symbols that compose the conjunction.
size_t size () const
Returns the number of symbols that compose the conjunction.
bool is_empty () const
Returns true if the conjunction is empty.
plVariableType get_var_type () const
Returns the variable's type as a 'plVariableType' value, where plVariableType is defined as an enum: enum {PL_INTEGER, PL_REAL, PL_CONINUOUS_INTERVAL, PL_DISCRETE_INTERVAL, PL_LABEL, PL_UNKNOWN_TYPE}.
plType get_type () const
Returns the variable's type as a 'plType' object.
virtual std::string name () const
Gets the variable name, given by the user.
std::vector< std::string > get_names () const
Get the names of all the variables in the conjunction.
const_iterator begin () const
Returns a const_iterator to the first variable in this conjunction.
const_iterator end () const
Returns a const_iterator pointing one item after the last variable in this conjunction.
bool contains (const plVariablesConjunction &other) const
Tests if this conjunction is a superset of 'other'.
bool has_same_symbols_as (const plVariablesConjunction &other) const
Tests if this conjunction has the same symbols as 'other'.
plVariablesConjunction & operator= (const plVariablesConjunction &other)
Assignment operator.
plVariablesConjunction & assign_from (const plVariablesConjunction &other)
Same as operator=()
plVariablesConjunction (const plVariablesConjunction &other)
Copy constructor.
void get_all_symbols (std::vector< plSymbol > &symbols) const
Convert the plVariablesConjunction into a vector of plSymbol objects.
std::vector< plSymbol > as_symbol_vector () const
Same as get_all_symbols() but returns the vector by value.
plSymbol operator[] (size_t n) const
Get the n^th symbol of the conjunction.
plSymbol at (size_t n) const
Get the n^th symbol of the conjunction.
bool operator== (const plVariablesConjunction &other) const
Return true if this and the other object are the same.
bool equal (const plVariablesConjunction &other) const
Return true if this and the other object are the same.
bool operator!= (const plVariablesConjunction &other) const
Return true if this and the other object are not the same.
bool not_equal (const plVariablesConjunction &other) const
Return true if this and the other object are not the same.
int get_symbol_position (const plSymbol &s) const
Return the position of a given symbol in the conjunction.
plVariablesConjunction & operator^= (const plVariablesConjunction &var)
In place concatenation of the variable var (at right side of the operator) with the variable at left side.
plVariablesConjunction & push_back (const plVariablesConjunction &var)
In place concatenation of the variable var (at right side of the operator) with the variable at left side.
plVariablesConjunction & remove (const plSymbol &symbol)
Remove one symbol from the variable conjunction and return a reference to the conjunction.
void clear ()
Clear the conjunction.
plSymbol get_symbol_with_name (const std::string &name) const
Returns the first symbol having name as print name.
plVariablesConjunction operator- (const plVariablesConjunction &other) const
Difference operator.
plVariablesConjunction subtract (const plVariablesConjunction &other) const
Difference.
plVariablesConjunction sort_by_name () const
Get a sorted-by-name copy of the conjunction.
plVariablesConjunction get_discrete_variables () const
Get the discrete variables of the conjunction.
bool operator< (const plVariablesConjunction &other) const
"Less than" operator
bool less (const plVariablesConjunction &other) const
"Less than"
Public Member Functions inherited from plObject
plObject ()
Constructor.
virtual ~plObject ()
Destroys the object.
std::string to_string (std::ostringstream *s=0) const
Returns the object as a string.
Static Public Member Functions
static const
plVariablesConjunction & empty ()
Return the empty variable conjunction.
Protected Member Functions
plVariablesConjunction (const kplVariableList &kernel_variable_list)
Constructor using a list of kplVariables.
plVariablesConjunction (kplVariable *kernel_variable)
Constructor using one kplVariable.
void cleanup ()
clean up the variable list
virtual void Output (std::ostream &out) const
Writes the variable at the output given by "out".
Protected Attributes
size_t Dsize_
Size of the variable list (variable_list), faster that the acces to size() function.
kplVariableList variable_list_
List of the function arguments variables.
kplVariableSet variable_set_
Mirrors variable_list_.
kplModVariableVector variable_vector_
Mirrors variable_list_.
Detailed Description
The plVariablesConjunction class implements the conjunction of a set of variables.
Member Typedef Documentation
typedef plVariablesConjunction_const_iterator plVariablesConjunction::const_iterator
Associated const_iterator.
Constructor & Destructor Documentation
virtual plVariablesConjunction::~plVariablesConjunction () virtual
Destructor, if the variable represents a list erase the list but not the variables on the list.
If empty variable, erase the empty variable
Member Function Documentation
plSymbol plVariablesConjunction::at (size_t n) const
Get the n^th symbol of the conjunction.
long double plVariablesConjunction::cardinality () const
Returns the number of values taken by the variable conjunction.
For example, if a variable 'x' takes 10 possible values and another variable 'y' takes 3 possible values, then the conjunction x^y takes 30 (10 x 3) possible values. It returns zero if the variable is not discretized (ie, non-discretized plRealType)
Referenced by plProbTable::plProbTable().
plVariablesConjunction plVariablesConjunction::concatenate (const plVariablesConjunction & variable) const inline
Return the concatenation of the variable var (at right side of the operator) with the variable at left side.
If a variable is found twice, only the first occurrence will be kept and a warning 62 will be raised.
bool plVariablesConjunction::contains (const plVariablesConjunction & other) const
Tests if this conjunction is a superset of 'other'.
(a ^ b).contains(a) == true (a ^ b).contains(b) == true (a ^ b).contains(c) == false (a ^ b ^ c).contains(a ^ b) == true (a ^ b ^ c).contains(a ^ b ^ d) == false
static const plVariablesConjunction& plVariablesConjunction::empty () static
Return the empty variable conjunction.
Referenced by plNonCndLearnObject::get_right_variables().
bool plVariablesConjunction::equal (const plVariablesConjunction & other) const inline
Return true if this and the other object are the same.
void plVariablesConjunction::get_all_symbols (std::vector< plSymbol > & symbols) const
Convert the plVariablesConjunction into a vector of plSymbol objects.
std::vector<std::string> plVariablesConjunction::get_names () const
Get the names of all the variables in the conjunction.
int plVariablesConjunction::get_symbol_position (const plSymbol & s) const
Return the position of a given symbol in the conjunction.
Return -1 if the symbol is not found.
plSymbol plVariablesConjunction::get_symbol_with_name (const std::string & name) const
Returns the first symbol having name as print name.
Raises an exception if no symbol with this print name is found.
plType plVariablesConjunction::get_type () const
Returns the variable's type as a 'plType' object.
In the case of a conjunction, the type of the first variable is returned. The returned object can in turn be converted into the appropriate derived class (plIntegerType, plRealType, plContinuousIntervalType, ...) so you can use its specialized methods and query its characteristics. In order to know into which class the object has to be converted, use the get_var_type() method.
Referenced by plODBCDataDescriptor::set_variables(), and plMysqlDataDescriptor::set_variables().
plVariableType plVariablesConjunction::get_var_type () const
Returns the variable's type as a 'plVariableType' value, where plVariableType is defined as an enum: enum {PL_INTEGER, PL_REAL, PL_CONINUOUS_INTERVAL, PL_DISCRETE_INTERVAL, PL_LABEL, PL_UNKNOWN_TYPE}.
In the case of a multi-dimensional conjunction, the type of the first variable is returned.
Referenced by plODBCDataDescriptor::set_variables(), and plMysqlDataDescriptor::set_variables().
const kplVariableList& plVariablesConjunction::get_variable_list () const inline
Needed by the Python bindings, but not part of the user API.
Please do not use.
Referenced by plExternalFunction::plExternalFunction(), and plExternalProbFunction::plExternalProbFunction().
bool plVariablesConjunction::has_same_symbols_as (const plVariablesConjunction & other) const
Tests if this conjunction has the same symbols as 'other'.
(a ^ b).has_same_symbols_as(b ^ a) == true; (a ^ b).has_same_symbols_as(b ^ a ^ c) == false; (a ^ b).has_same_symbols_as(b) == false;
bool plVariablesConjunction::is_continuous () const
Returns true if the conjunction contains only continuous symbols (ie, plRealType or plContinuousIntervalType), false otherwise.
bool plVariablesConjunction::is_discrete () const
Returns true if the conjunction contains only discrete symbols, false otherwise.
bool plVariablesConjunction::is_discretized () const
Returns true if the conjunction contains only discretizable symbols (ie, all types excluding non-discretized plRealType), false otherwise.
bool plVariablesConjunction::is_empty () const inline
Returns true if the conjunction is empty.
Referenced by plMatrixDataDescriptor< T >::observed_variables(), plODBCDataDescriptor::observed_variables(), plMysqlDataDescriptor::observed_variables(), plODBCDataDescriptor::set_variables(), and plMysqlDataDescriptor::set_variables().
virtual std::string plVariablesConjunction::name () const virtual
Gets the variable name, given by the user.
In the case of a conjunction, the type of the first variable is returned.
Reimplemented in plArray.
bool plVariablesConjunction::not_equal (const plVariablesConjunction & other) const inline
Return true if this and the other object are not the same.
bool plVariablesConjunction::operator!= (const plVariablesConjunction & other) const inline
Return true if this and the other object are not the same.
Referenced by plType::not_equal().
bool plVariablesConjunction::operator== (const plVariablesConjunction & other) const
Return true if this and the other object are the same.
Referenced by plType::equal().
plSymbol plVariablesConjunction::operator[] (size_t n) const
Get the n^th symbol of the conjunction.
plVariablesConjunction plVariablesConjunction::operator^ (const plVariablesConjunction & variable) const
Return the concatenation of the variable var (at right side of the operator) with the variable at left side.
If a variable is found twice, only the first occurrence will be kept and a warning 62 will be raised.
plVariablesConjunction& plVariablesConjunction::operator^= (const plVariablesConjunction & var)
In place concatenation of the variable var (at right side of the operator) with the variable at left side.
If a variable is found twice, only the first occurrence will be kept and a warning 62 will be raised.
WARNING: This operator has effect only on base plVariablesConjunction objects. For all subclasses this operator does not have any effect (e.g. You can't use a plSymbol at the left side of the operator).
plVariablesConjunction& plVariablesConjunction::push_back (const plVariablesConjunction & var) inline
In place concatenation of the variable var (at right side of the operator) with the variable at left side.
If a variable is found twice, only the first occurrence will be kept and a warning 62 will be raised.
WARNING: This operator has effect only on base plVariablesConjunction objects. For all subclasses this operator does not have any effect (e.g. You can't use a plSymbol at the left side of the operator).
Member Data Documentation
kplVariableSet plVariablesConjunction::variable_set_ mutable protected
Mirrors variable_list_.
variable_set_ may be empty, use variable_set() to make sure it is valid and get it. Used to speed up operator^=().
kplModVariableVector plVariablesConjunction::variable_vector_ mutable protected
Mirrors variable_list_.
variable_vector_ may be empty, use variable_vector() to make sure it is valid and get it. Used to speed up operator[](size_t).