ProBT: plODBCDataConnector Class Reference
plODBCDataConnector Class Reference
This class implements an ODBC data sources connector.
Public Member Functions
plODBCDataConnector ()
Constructor.
~plODBCDataConnector ()
Destructor.
void set_driver (const std::string &db_server, const std::string &db_login, const std::string &db_password, const std::string &db_name, const std::string &db_port, const std::string &driver_name)
Define connection parameters.
bool connect ()
Connect to the database.
void disconnect ()
Disconnect from the database.
bool run_query (const std::string &strQuery)
Execute a query using the database connection.
int get_num_fields () const
Obtain the number of fields in the query.
int get_num_rows () const
Return the number of rows returned by the query.
SQLRETURN first ()
Goto the first row of query result.
SQLRETURN next ()
Goto the next row of query result.
template<typename T >
void set_column_value_type (unsigned int numColumn)
Set a given column type.
template<typename T >
T get_column_value (unsigned int numColumn) const
Obtain the value of a given column.
bool get_column_def (unsigned int numColumn) const
Return true if the column is defined (not NULL).
bool is_connected () const
Return connection status.
Detailed Description
This class implements an ODBC data sources connector.
Member Function Documentation
bool plODBCDataConnector::connect () inline
Connect to the database.
void plODBCDataConnector::disconnect () inline
Disconnect from the database.
Referenced by ~plODBCDataConnector().
SQLRETURN plODBCDataConnector::first () inline
Goto the first row of query result.
Referenced by plODBCDataDescriptor::rewind().
bool plODBCDataConnector::get_column_def (unsigned int numColumn) const inline
Return true if the column is defined (not NULL).
Return false if the column is not defined (NULL).
Returns
true if the column is defined (not NULL). Return false if the column is not defined (NULL).
Referenced by plODBCDataDescriptor::get_data_record().
template<typename T > T plODBCDataConnector::get_column_value (unsigned int numColumn) const inline
Obtain the value of a given column.
Parameters
[in] numColumn column's number
Returns
the value of the column
This template method is instantiated for int, unsigned int, float, double, long double, and std::string
int plODBCDataConnector::get_num_fields () const inline
Obtain the number of fields in the query.
Returns
the number of fields in the query
Referenced by run_query().
int plODBCDataConnector::get_num_rows () const inline
Return the number of rows returned by the query.
Returns
the number of rows returned by the query
Referenced by plODBCDataDescriptor::get_n_records().
bool plODBCDataConnector::is_connected () const inline
Return connection status.
Returns
true if the connection is established. Return false otherwise.
SQLRETURN plODBCDataConnector::next () inline
Goto the next row of query result.
Referenced by plODBCDataDescriptor::get_data_record().
bool plODBCDataConnector::run_query (const std::string & strQuery) inline
Execute a query using the database connection.
Parameters
[in] strQuery the query to be executed.
Returns
true if the query is executed successfully. Return false otherwise.
References get_num_fields().
template<typename T > void plODBCDataConnector::set_column_value_type (unsigned int numColumn) inline
Set a given column type.
Parameters
[in] numColumn column's number.
This template method is instantiated for int, unsigned int, float, double, long double, and std::string
void plODBCDataConnector::set_driver (const std::string & db_server, const std::string & db_login, const std::string & db_password, const std::string & db_name, const std::string & db_port, const std::string & driver_name) inline
Define connection parameters.
Parameters
[in] db_server Host name (address)
[in] db_login Database user name
[in] db_password User's password
[in] db_name Database name
[in] db_port Port number
[in] driver_name Driver name