# This file was automatically generated by the ProBT Makefile.
# It describes how to compile and run programs using this ProBT package.
# You may include it in your own Makefile.
# Define PROBT_ROOT before including this file.
# Flags passed to the C++ compiler.
PROBT_CFLAGS := -I"$(PROBT_ROOT)/include"
# Search path for libraries at runtime.
PROBT_DLL_PATH := $(PROBT_ROOT)/lib
# Flags passed to the C++ linker.
PROBT_LDFLAGS := -L"$(PROBT_ROOT)/lib" -lspl
# Flags passed to the C# compiler for using ProBT.NET.
PROBT_CSFLAGS := -r:"$(PROBT_ROOT)/lib/plnet.dll"
